/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.64
 * Generated at: 2015-10-16 08:42:16 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/header.txt", Long.valueOf(1444907562000L));
    _jspx_dependants.put("/footer.txt", Long.valueOf(1444907562000L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\n");
      out.write("<title>Product Information</title>\n");
      out.write("<link rel=\"stylesheet\" href=\"tablesorter/themes/blue/style.css\" type=\"text/css\" id=\"\" media=\"print, projection, screen\" />\n");
      out.write("\n");
      out.write("<script type=\"text/javascript\" \n");
      out.write("\tsrc=\"jquery/jquery-1.11.2.js\"></script>\n");
      out.write("<script type=\"text/javascript\" \n");
      out.write("\tsrc=\"tablesorter/jquery.tablesorter.js\"></script>\n");
      out.write("\n");
      out.write("\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("\t$(function(){\n");
      out.write("\t\t$(\"table\").tablesorter();\n");
      out.write("\t\t$(\"input:first\").focus();\n");
      out.write("\t});\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("<style type=\"text/css\">\n");
      out.write("\t* {\n");
      out.write("\t\tfont-family: helvetica !important;\n");
      out.write("\t}\n");
      out.write("\ttable th, table td {\n");
      out.write("\t\tfont-size: 1.2em !important;\n");
      out.write("\t}\n");
      out.write("\t.header {\n");
      out.write("\t\tcursor: pointer;\n");
      out.write("\t\ttext-align: left;\n");
      out.write("\t\tfont-size: 1.1em;\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\t.footer {\n");
      out.write("\t\tmargin-top: 100px;\n");
      out.write("\t\ttext-align: center;\n");
      out.write("\t\tpadding: 25px;\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\t.form label {\n");
      out.write("\t\tdisplay: inline-block;\n");
      out.write("\t\twidth: 150px;\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\t.form div {\n");
      out.write("\t\tmargin: 10px 0;\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\t.form div input {\n");
      out.write("\t\tpadding: 4px;\n");
      out.write("\t\tborder-color: #ccc;\n");
      out.write("\t\tborder-radius: 3px;\n");
      out.write("\t\tborder-width: 1px;\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\t.links a {\n");
      out.write("\t\tpadding: 10px;\n");
      out.write("\t\tpadding-left: 0;\n");
      out.write("\t\tmargin: 5px 10px 5px 0;\n");
      out.write("\t\tborder-radius: 5px;\n");
      out.write("\t}\n");
      out.write("\t.links a:hover {\n");
      out.write("\t\tbox-shadow: 0 0 20px #aaa;\n");
      out.write("\t}\n");
      out.write("</style>\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("<h1>Northwind Inc.</h1>\n");
      out.write("<h2>Product Data</h2>\n");
      out.write("\n");
      out.write("<div class=\"links\">\n");
      out.write("<a href=\"./\">Home</a>\n");
      out.write("<a href=\"./viewAllProducts\">All products</a>\n");
      out.write("<a href=\"./viewProductsByPrice\">Products by price</a>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<hr />\n");

	String message = (String)request.getAttribute("message");
	if(message==null) {
		message = "";
	}	

      out.write("\n");
      out.write("<h3>");
      out.print( message );
      out.write("</h3>\n");
      out.write("\n");
      out.write("\n");
      out.write("<h3>This is the homepage</h3>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<div class=\"footer\">\n");
      out.write("&copy; 2015 all rights reserved\n");
      out.write("</div>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
